version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: capital
    env_file:
      -  .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5433}