name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4

    # Setup Node.js and cache dependencies for the backend
    - name: Use Node.js ${{ matrix.node-version }} for backend
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies for backend
      run: npm ci
      working-directory: backend

    - name: Build backend
      run: npm run build --if-present
      working-directory: backend

    # Setup Node.js and cache dependencies for the frontend
    - name: Use Node.js ${{ matrix.node-version }} for frontend
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies for frontend
      run: npm ci
      working-directory: frontend

    - name: Build frontend
      run: npm run build --if-present
      working-directory: frontend
